export class UserModel {
     UserId :number;
     NameOfCompany:string;
     Street: string ;
     PostalCode: string ;
     Place: string ;
     AccountHolder: string ;
     Bank: string ;
     IBAN: string ;
     BICCode: string ;
     GroupIds: string ;
     SubGroupId: string ;
     LEINumber: string ;
     FurtherField4: string ;
     Salutation: number ;
     Title: string ;
     FirstName: string ;
     SurName: string ;
     ContactNumber: string ;
     EmailAddress: string ;
     UserName: string ;
     Password: string ;
     FurtherField1: string ;
     FurtherField2: string ;
     FurtherField3: string ;
     UserTypeId: string ;
     RatingAgentur1: string ;
     RatingAgenturValue1: string ;
     RatingAgentur2: string ;
     RatingAgenturValue2: string ;
     DepositInsurance: number ;
     ClientGroupId: number ;
     AgreeToThePrivacyPolicy: boolean ;
     GroupCommunities: boolean ;
     GroupCompanyGMBH: boolean ;
     GroupCompany: boolean ;
     AgreeToTheRatingsMayPublish: boolean ;
     AgreeThatInformationOfCompanyMayBePublished: boolean ;
     AcceptAGBS: boolean ;
     DateCreated: Date ;
     DateModified: Date ;
     ModifiedBy: number ;
     rdbNonBank:boolean;
     rdbBank:boolean;
     NewPassword:string;
     CommercialRegisterExtract: any;
     IdentityCard: any;
}
